### ISSUE TITLE
Kraken x73 Sync Issue

### ISSUE THREAD

**Issue by ZeldaFan101** [Sajyd/NZXTConnect#1]
![C4F0DF33-934E-4EB1-8B12-C21A39558782](https://user-images.githubusercontent.com/81413218/112610912-d4f6c700-8de2-11eb-8a02-a859187663ce.jpeg)

The pump LEDs are syncing, but the fans are not (front mounted).

**Comment by Sajyd** [comment]
This software will only sync the pump leds. You should check for a software that sync your led hub to razer chroma like you did for the other three i suppose
