### ISSUE TITLE
Kraken X63 issue

### ISSUE THREAD

**Issue by Patrick378** [Sajyd/NZXTConnect#2]
My nzxt kraken x63 shows up a device in chroma studio but it shows up with only 4 leds.
The kraken x63 has a total of 9 leds, 1 on the logo and 8 on the ring.
Could you fix this? Or maybe make it as led strip, this way its better to controll the lighting effects.
![chroma](https://user-images.githubusercontent.com/81139774/131225180-287818a0-507d-4879-862a-1eb85ef26a15.png)

**Comment by Sajyd** [comment]
Won't do, it's basically a tweak of AuraConnect which supports 4 simultaneous colors at the version used for NZXTConnect. AuraConnect should be modified which isn't mine plus it has bean fully revamped
